# Generated by Django 4.2.25 on 2025-10-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('character_frequency_map', models.JSONField()),
                ('is_palindrome', models.BooleanField()),
            ],
        ),
    ]
